// DO NOT EDIT. This file is automatically generated.
import type { Manifest } from 'kretes';

import * as $0 from "./routes/index.page.tsx";
import * as $1 from "./routes/posts.ts";

const manifest: Manifest = {
  routes: {
    '/': $0,
    '/posts': $1,
  },
};

export default manifest;
